export const loaderConstants = {
  SHOW_LOADER_REQUEST: 'SHOW_LOADER_REQUEST',
  SHOW_LOADER_SUCCESS: 'SHOW_LOADER_SUCCESS',
  PRIMARY_LOADER_START_REQUEST: 'PRIMARY_LOADER_START_REQUEST',
  PRIMARY_LOADER_START_SUCCESS: 'PRIMARY_LOADER_START_SUCCESS',
  PRIMARY_LOADER_STOP_REQUEST: 'PRIMARY_LOADER_STOP_REQUEST',
  PRIMARY_LOADER_STOP_SUCCESS: 'PRIMARY_LOADER_STOP_SUCCESS',
};

